// ServerEvents.recipes(event => {
//     event.recipes.gtceu.mob_loot_fabrication('8x minecraft:rotten_flesh')
//         .itemInputs()
//         .notConsumable('kubejs:full_zombie_matrix')
//         .itemOutputs('8x minecraft:rotten_flesh')
//         .duration(100)
//         .EUt(30)
//         .circuit(0)
//     event.recipes.gtceu.mob_loot_fabrication('minecraft:iron_ingot')
//         .itemInputs()
//         .notConsumable('kubejs:full_zombie_matrix')
//         .itemOutputs('minecraft:iron_ingot')
//         .duration(100)
//         .EUt(30)
//         .circuit(1)
//     event.recipes.gtceu.mob_loot_fabrication('2x minecraft:potato')
//         .itemInputs()
//         .notConsumable('kubejs:full_zombie_matrix')
//         .outputFluids(Fluid.of('gtceu:iron', 144))
//         .duration(100)
//         .EUt(30)
//         .circuit(2)
//     event.recipes.gtceu.mob_loot_fabrication('2x minecraft:carrot')
//         .itemInputs()
//         .notConsumable('kubejs:full_zombie_matrix')
//         .itemOutputs('2x minecraft:carrot')
//         .duration(100)
//         .EUt(30)
//         .circuit(3)
//     event.recipes.gtceu.mob_loot_fabrication('2x minecraft:potato')
//         .itemInputs()
//         .notConsumable('kubejs:full_zombie_matrix')
//         .itemOutputs('2x minecraft:potato')
//         .duration(100)
//         .EUt(30)
//         .circuit(4)
// })